apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: default
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: YWRtaW4=  # Base64-encoded username "admin"
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=  # Base64-encoded password "admin"
